server:
  port: 9191

spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Auto routes via service discovery
      routes:
        - id: admin-route
          uri: lb://ADMIN-MS
          predicates:
            - Path=/admin/**
        - id: auth-route
          uri: lb://AUTH-MS
          predicates:
            - Path=/auth/**
        - id: booking-route
          uri: lb://BOOKING-MS
          predicates:
            - Path=/booking/**
        - id: inventory-route
          uri: lb://INVENTORY-MS
          predicates:
            - Path=/inventory/**
        - id: payment-route
          uri: lb://PAYMENT-MS
          predicates:
            - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
