spring:
  application:
    name: auth-ms
  datasource:
    url: jdbc:mysql://localhost:3306/busdb
    username: bususer
    password: buspass

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
