spring:
  application:
    name: booking-ms

  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: bookinguser
    password: Booking@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka














#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookingdb
#    username: bookinguser
#    password: Booking@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8082

















#server:
#  port: 8082
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookingdb
#    username: bookinguser
#    password: Booking@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##spring:
##  application:
##    name: booking-ms
##  datasource:
##    url: jdbc:mysql://localhost:3306/busdb
##    username: bususer
##    password: buspass
##
##server:
##  port: 8084
##
##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:8761/eureka/
