server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/kaush/Documents/bus-reservation-microservices/config-server/config-repo
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
